\documentclass[a4paper]{article}

\title{Sweave Example 1}

\author{Friedrich Leisch}

\begin{document}

\maketitle

In this example we embed parts of the examples from the


<<>>=
a = runif(1000)
print(summary(a))

@

which shows that the location parameter of the Ozone

distribution varies significantly from month to month . Finally we

include a boxplot of the data :

\begin{center}
<<fig = TRUE , echo = FALSE>>=
plot(a)
@

\end{center}

\end{document}
